In [1]:
import pandas as pd

## Технічна колонка з назвами країн малими буквами

In [3]:
df=pd.read_excel("countries_to_prepare.xlsx")
df["Link_lower"]=df["Link"].str.lower()

## Масив з назвою країни представленою останнім словом

In [7]:
array=[]

for cell in df["Link_lower"]:
    dd=cell.rsplit(' ', 1)[-1]
    array.append(dd)
    
df['Last_word']=array
df

              Link     Link_lower    Last_word
0        Австралия      австралия    австралия
1          Австрия        австрия      австрия
2      Азербайджан    азербайджан  азербайджан
3          Албания        албания      албания
4            Алжир          алжир        алжир
..             ...            ...          ...
193       Британия       британия     британия
194        Оссетия        оссетия      оссетия
195        Абхазия        абхазия      абхазия
196          Запад          запад        запад
197  Штаты Америки  штаты америки      америки

[198 rows x 3 columns]

## Результат

In [10]:
df["first_letters"]=df["Last_word"].str[:-2]

df["processed"]=df["first_letters"]+'([А-Яа-яЁёЇїЄєЭэЪъ]+)?'
final=df[["Link", "processed"]]
final.to_excel('countries_to_finish_manually.xlsx')
               
final

              Link                        processed
0        Австралия    австрал([А-Яа-яЁёЇїЄєЭэЪъ]+)?
1          Австрия      австр([А-Яа-яЁёЇїЄєЭэЪъ]+)?
2      Азербайджан  азербайдж([А-Яа-яЁёЇїЄєЭэЪъ]+)?
3          Албания      албан([А-Яа-яЁёЇїЄєЭэЪъ]+)?
4            Алжир        алж([А-Яа-яЁёЇїЄєЭэЪъ]+)?
..             ...                              ...
193       Британия     британ([А-Яа-яЁёЇїЄєЭэЪъ]+)?
194        Оссетия      оссет([А-Яа-яЁёЇїЄєЭэЪъ]+)?
195        Абхазия      абхаз([А-Яа-яЁёЇїЄєЭэЪъ]+)?
196          Запад        зап([А-Яа-яЁёЇїЄєЭэЪъ]+)?
197  Штаты Америки      амери([А-Яа-яЁёЇїЄєЭэЪъ]+)?

[198 rows x 2 columns]

## Далі залишається вручну поправити корені слів, і абревіатури, де код відрізав забагато